# Using the MNIST Dataset to recognize digits

In [51]:
import math
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import gzip
import pickle

In [52]:
with gzip.open('mnist.pkl.gz', 'rb') as f:
    train_set, valid_set, test_set = pickle.load(f, encoding='iso-8859-1')

train_x, train_y = train_set

#plt.imshow(train_x[0].reshape((28, 28)), cmap=cm.Greys_r)
#plt.show()


In [53]:
#input array
x = []

#expected output
y = []

In [54]:
#create a neural network class
class nn(object):
    def __init__ (self):
        self.inSize = 784
        self.hiddenSize = 15
        self.outSize = 10
            
        #randomly initialize the weights
        self.ihW = np.random.rand(self.inSize, self.hiddenSize)
        self.hoW = np.random.rand(self.hiddenSize, self.outSize)
        
    def forwardprop(self, inp):
        self.z = np.dot(inp, self.ihW)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot (self.z2, self.hoW)
        final = self.sigmoid(self.z3)
        return final
    
    def sigmoid(self,z):
        return (1 / (1 + np.exp(-z)))

In [55]:
#sigmoid function
def sigmoid(z):
    return (1 / (1 + np.exp(-z)))

def sigmoid_prime(z):
    return z*(1-z)

In [56]:
yhat = []

for i in range(0, (np.size(train_x)-1)):
    x = train_x[i]
    NeuralNet = nn()
    output = NeuralNet.forwardprop(x)
    guess = np.argmax(output)
    guess = guess 
    yhat = np.append(yhat,guess)
    y = np.append(y, train_y[i])
    print(y)
    print(yhat)

[5.]
[6.]
[5. 0.]
[6. 1.]
[5. 0. 4.]
[6. 1. 2.]
[5. 0. 4. 1.]
[6. 1. 2. 9.]
[5. 0. 4. 1. 9.]
[6. 1. 2. 9. 0.]
[5. 0. 4. 1. 9. 2.]
[6. 1. 2. 9. 0. 9.]
[5. 0. 4. 1. 9. 2. 1.]
[6. 1. 2. 9. 0. 9. 4.]
[5. 0. 4. 1. 9. 2. 1. 3.]
[6. 1. 2. 9. 0. 9. 4. 9.]
[5. 0. 4. 1. 9. 2. 1. 3. 1.]
[6. 1. 2. 9. 0. 9. 4. 9. 8.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7.]
[5. 0. 4. 1. 9

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 6. 3. 3. 6. 6. 5. 4. 4. 3. 9. 2. 4. 7. 4. 9. 3. 2. 7. 2.
 9. 6. 7. 1. 8. 1. 4. 1. 2. 9. 2. 0. 6. 0. 9. 2. 0. 3. 5. 7. 6. 4. 9. 7.
 2. 6.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2.

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 6. 3. 3. 6. 6. 5. 4. 4. 3. 9. 2. 4. 7. 4. 9. 3. 2. 7. 2.
 9. 6. 7. 1. 8. 1. 4. 1. 2. 9. 2. 0. 6. 0. 9. 2. 0. 3. 5. 7. 6. 4. 9. 7.
 2. 6. 3. 7. 7. 7. 1. 1. 9. 0. 3. 9. 8. 2. 0. 0. 8. 9. 2. 3. 2. 1. 9. 4.
 6. 9. 9. 8. 5. 7. 5. 6. 0. 5. 6. 5. 0. 6. 8. 3. 0. 6. 7. 8. 7. 1. 0. 7.
 0. 3. 0. 7. 6. 7.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 6. 3. 3. 6. 6. 5. 4. 4. 3. 9. 2. 4. 7. 4. 9. 3. 2. 7. 2.
 9. 6. 7. 1. 8. 1. 4. 1. 2. 9. 2. 0. 6. 0. 9. 2. 0. 3. 5. 7. 6. 4. 9. 7.
 2. 6. 3. 7. 7. 7. 1. 1. 9. 0. 3. 9. 8. 2. 0. 0. 8. 9. 2. 3. 2. 1. 9. 4.
 6. 9. 9. 8. 5. 7. 5. 6. 0. 5. 6. 5. 0. 6. 8. 

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 6. 3. 3. 6. 6. 5. 4. 4. 3. 9. 2. 4. 7. 4. 9. 3. 2. 7. 2.
 9. 6. 7. 1. 8. 1. 4. 1. 2. 9. 2. 0. 6. 0. 9. 2. 0. 3. 5. 7. 6. 4. 9. 7.
 2. 6. 3. 7. 7. 7. 1. 

 9. 4. 0. 5. 8. 5. 7. 2. 8. 7. 0. 2. 4. 9. 2. 0.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 6. 3.

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 

 0. 9. 5. 4. 9. 9. 0. 8. 6. 0. 0. 1. 1. 4.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6.

 8. 9. 4. 1. 5. 2. 2. 9. 0. 3. 9. 6. 7. 2.]
[6. 1. 2. 9. 0. 9. 4. 9. 8. 0. 6. 4. 0. 3. 0. 2. 7. 3. 3. 4. 2. 3. 6. 6.
 9. 3. 7. 8. 6. 1. 6. 2. 7. 9. 8. 3. 6. 2. 4. 1. 4. 7. 8. 9. 3. 0. 8. 2.
 5. 4. 4. 2. 6. 6. 3. 3. 6. 6. 5. 4. 4. 3. 9. 2. 4. 7. 4. 9. 3. 2. 7. 2.
 9. 6. 7. 1. 8. 1. 4. 1. 2. 9. 2. 0. 6. 0. 9. 2. 0. 3. 5. 7. 6. 4. 9. 7.
 2. 6. 3. 7. 7. 7. 1. 1. 9. 0. 3. 9. 8. 2. 0. 0. 8. 9. 2. 3. 2. 1. 9. 4.
 6. 9. 9. 8. 5. 7. 5. 6. 0. 5. 6. 5. 0. 6. 8. 3. 0. 6. 7. 8. 7. 1. 0. 7.
 0. 3. 0. 7. 6. 7. 5. 8. 9. 7. 3. 2. 8. 7. 6. 7. 5. 6. 2. 6. 1. 1. 2. 8.
 9. 1. 4. 8. 8. 5. 1. 9. 7. 1. 3. 3. 3. 0. 7. 3. 4. 6. 2. 2. 6. 4. 4. 1.
 8. 6. 4. 0. 9. 1. 4. 3. 9. 0. 0. 8. 4. 7. 3. 6. 3. 9. 9. 1. 9. 4. 6. 4.
 2. 5. 0. 7. 1. 7. 7. 7. 3. 1. 7. 0. 4. 4. 9. 1. 6. 1. 4. 2. 6. 7. 8. 1.
 9. 4. 0. 5. 8. 5. 7. 2. 8. 7. 0. 2. 4. 9. 2. 0. 2. 2. 2. 1. 0. 3. 3. 6.
 3. 5. 8. 2. 5. 6. 4. 1. 8. 1. 7. 1. 8. 5. 3. 9. 0. 2. 1. 8. 3. 4. 0. 8.
 0. 9. 5. 4. 9. 9. 0. 8. 6. 0. 0. 1. 1. 4. 5. 5. 7. 0. 8. 6. 5. 2. 8. 2.
 6. 8. 

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6. 0. 9. 7. 5. 7. 2. 1. 1. 6.
 8. 9. 4. 1. 5. 2. 2. 9. 0. 3. 9. 6. 7. 2. 0. 3. 5.

 4. 5. 4. 8. 1. 9. 1. 1. 8. 2. 2.]
[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6. 0. 9. 7. 5. 7. 2. 1. 1. 6.
 8. 9. 4. 1. 5. 

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6. 0. 9. 7. 5. 7. 2. 1. 1. 6.
 8. 9. 4. 1. 5. 2. 2. 9. 0. 3. 9. 6. 7. 2. 0. 3. 5.

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6. 0. 9. 7. 5. 7. 2. 1. 1. 6.
 8. 9. 4. 1. 5. 2. 2. 9. 0. 3. 9. 6. 7. 2. 0. 3. 5.

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6. 0. 9. 7. 5. 7. 2. 1. 1. 6.
 8. 9. 4. 1. 5. 2. 2. 9. 0. 3. 9. 6. 7. 2. 0. 3. 5.

[5. 0. 4. 1. 9. 2. 1. 3. 1. 4. 3. 5. 3. 6. 1. 7. 2. 8. 6. 9. 4. 0. 9. 1.
 1. 2. 4. 3. 2. 7. 3. 8. 6. 9. 0. 5. 6. 0. 7. 6. 1. 8. 7. 9. 3. 9. 8. 5.
 9. 3. 3. 0. 7. 4. 9. 8. 0. 9. 4. 1. 4. 4. 6. 0. 4. 5. 6. 1. 0. 0. 1. 7.
 1. 6. 3. 0. 2. 1. 1. 7. 9. 0. 2. 6. 7. 8. 3. 9. 0. 4. 6. 7. 4. 6. 8. 0.
 7. 8. 3. 1. 5. 7. 1. 7. 1. 1. 6. 3. 0. 2. 9. 3. 1. 1. 0. 4. 9. 2. 0. 0.
 2. 0. 2. 7. 1. 8. 6. 4. 1. 6. 3. 4. 5. 9. 1. 3. 3. 8. 5. 4. 7. 7. 4. 2.
 8. 5. 8. 6. 7. 3. 4. 6. 1. 9. 9. 6. 0. 3. 7. 2. 8. 2. 9. 4. 4. 6. 4. 9.
 7. 0. 9. 2. 9. 5. 1. 5. 9. 1. 2. 3. 2. 3. 5. 9. 1. 7. 6. 2. 8. 2. 2. 5.
 0. 7. 4. 9. 7. 8. 3. 2. 1. 1. 8. 3. 6. 1. 0. 3. 1. 0. 0. 1. 7. 2. 7. 3.
 0. 4. 6. 5. 2. 6. 4. 7. 1. 8. 9. 9. 3. 0. 7. 1. 0. 2. 0. 3. 5. 4. 6. 5.
 8. 6. 3. 7. 5. 8. 0. 9. 1. 0. 3. 1. 2. 2. 3. 3. 6. 4. 7. 5. 0. 6. 2. 7.
 9. 8. 5. 9. 2. 1. 1. 4. 4. 5. 6. 4. 1. 2. 5. 3. 9. 3. 9. 0. 5. 9. 6. 5.
 7. 4. 1. 3. 4. 0. 4. 8. 0. 4. 3. 6. 8. 7. 6. 0. 9. 7. 5. 7. 2. 1. 1. 6.
 8. 9. 4. 1. 5. 2. 2. 9. 0. 3. 9. 6. 7. 2. 0. 3. 5.

KeyboardInterrupt: 